### PR TITLE
feat: Allow the use of custom discovery endpoint

### PR DESCRIPTION
**Pull request by ydrisR**
Thanks for this solid library.
On some occasions public services will expose OAuth2/OIDC endpoint on custom uri which are different from the standard patern you use in the library. I'd like to propose a new constructor to create a RelyingParty instances based on custom endpoints, different than what would be computed by the discovery method.

### CODE REVIEW

**Comment by fforootd** [comment]
@ydrisR thanks for the PR we will have a look on this in the next few day, hopefully your are not in a hurry 😁

**Comment by fforootd** [comment]
@ydrisR one question I have is... you want to configure explicit endpoints instead of using the once provided by the oidc discovery endpoint. Or do you want to configure a oidc rp without an oidc discovery endpoint on the op side?

**Comment by ydrisR** [comment]
> @ydrisR one question that I have is. Do you want to configure explicit endpoints instead of using the once provided by the oidc discovery endpoint, or do you want to configure a oidc rp without an oidc discovery endpoint on the op side?

The problem I faced is that my oidc provider decided to use a discovery endpoint which does not follow the standard patern you implemented in the library.
Here is the discovery endoint url: https://auth.bas.esw.esante.gouv.fr/auth/realms/esante-wallet/.well-known/wallet-openid-configuration 
Notice the extra "wallet-" which prevent method `oidc.client.Discover()` to work properly :(

I decided to create a new method to instantiate a new `RelyingParty` from a custom `DiscoveryConfiguration` as I thought it would give more flexibility: you can build the DiscoveryConfiguration manually or from a discovery endpoint, it's up to the developer.

For my specific situation I think we could address the problem with a simpler solution: if there was a way to set/override the constant `oidc.DiscoveryEndpoint` that would make the job.

**Comment by fforootd** [comment]
> The problem I faced is that my oidc provider decided to use a discovery endpoint which does not follow the standard patern you implemented in the library.

Ah I see 😁 
What an odd design choice. I mean the oidc discovery would allow [prefixed paths for multi tenancy reasons](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest).

@livio-a where do you stand on this. IMO we should allow to overwrite the oidc discovery url.

**Comment by oliverpool** [comment]
Another possible approach for this problem, would be to add a `*oidc.DiscoveryConfiguration` field on the `rp` struct, which could be set by an `Option` `WithDiscoveryConfiguration`.

In `NewRelyingPartyOIDC`, if this pointer is not nil, then it is used instead of calling `client.Discover`.

**Comment by ydrisR** [comment]
I like both solutions. Don't hesitate to ping me if you want me to implement one or the other :)

**Comment by livio-a** [comment]
Hey @ydrisR 

Thanks for great feedback and the issue. I have thought about it and agree with @fforootd:
IMO the most useful for your scenario would be to create an option to overwrite the discovery path. 

I think that providing a static configuration might make sense in very rare cases (not yours). If the OP only changes a single configuration, you'll have to change it as well and even recompile. Which kind of breaks the idea of the discovery endpoint.

Would you mind changing the PR to just overwrite the discovery path?

**Review by livio-a — APPROVED** [review]

**Comment by livio-a** [comment]
Thanks for your contribution @ydrisR !

**Pull request merged**
